baseURL = 'https://RHTE-2023-Edge-Lab.github.io/'
languageCode = 'en-us'
title = 'RHTE 2023 Edge Lab'

theme = 'hugo-theme-learn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "red"
openshift_domain = "cluster-GUID.GUID.sandboxID.opentlc.com"
